version: '3.4'

services:
  homepage:
    image: homepage:dev
    build:
      target: base
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_homepage$
    volumes:
      - C:\src\test\Sandbox-2.0\Homepage:/app
      - C:\Users\sarah.caldow\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_homepage$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_homepage$ bin/Debug/netcoreapp2.0/Homepage.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
